pull_request_rules:
  - name: Automatic merge
    conditions:
      - "author=javiyt"
      - base=master
    actions:
      merge:
        method: squash
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - base=master
    actions:
      merge:
        method: squash